name: Flask Docker Image Build

on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
    
env:
  DOCKER_IMAGE_NAME: flask_gunicorn
  DOCKER_IMAGE_TAG: ${{ github.run_id }}

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} .
